-- ═══════════════════════════════════════════════════════════════════
-- ClearCheck V3 — Reseed tscs with the full SOC 2 TSC set (43 criteria)
-- Migration: 0008_tscs_full_soc2_set.sql
--
-- Source of truth: Airtable "TSC Criteria" table (base appdGzMxm5KNKunLO,
-- table tblFEgjetnlrndgL2). Replaces the partial 9-row seed.
--
-- Upsert by tsc_code: the 9 existing codes are all within this set, so they
-- are UPDATED (ids + control_tscs links preserved) and the rest are INSERTED.
-- No deletes → no FK impact. trust_principle for PI* rows (blank in Airtable)
-- is derived as "Processing Integrity" to satisfy NOT NULL.
-- ═══════════════════════════════════════════════════════════════════

insert into tscs (tsc_code, trust_principle, common_criteria_category, description, points_of_focus, additional_points_of_focus) values
('A1.1', 'Availability', 'A1 - Availability', 'The entity maintains, monitors, and evaluates current processing capacity and use of system components (infrastructure, data, and software) to manage capacity demand and to enable the implementation of additional capacity to help meet its objectives.', '• Measures Current Usage — The use of the system components is measured to establish a baseline for capacity management and to use when monitoring and evaluating the risk of impaired availability due to capacity constraints. • Forecasts Capacity — The expected average and peak use of system components is forecasted and compared to system capacity and associated tolerances. Forecasting considers system resilience and capacity in the event of the failure of system components that constrain capacity. • Makes Changes Based on Forecasts — The system change management process is initiated when forecasted usage exceeds capacity tolerances. 
', NULL),
('A1.2', 'Availability', 'A1 - Availability', 'The entity authorizes, designs, develops or acquires, implements, operates, approves, maintains, and monitors environmental protections, software, data backup processes, and recovery infrastructure to meet its objectives.', '• Identifies Environmental Threats — As part of the risk assessment process, management identifies environmental threats that could impair the availability of the system, including threats resulting from adverse weather, failure of environmental control systems, electrical discharge, fire, and water. • Designs Detection Measures — Detection measures are implemented to identify anomalies that could result from environmental threat events. • Implements and Maintains Environmental Protection Mechanisms — Management implements and maintains environmental protection mechanisms to prevent and mitigate environmental events. • Implements Alerts to Analyze Anomalies — Management implements alerts that are communicated to personnel for analysis to identify environmental threat events. 
• Responds to Environmental Threat Events — Procedures are in place for responding to environmental threat events and for evaluating the effectiveness of those policies and procedures on a periodic basis. This includes automatic mitigation systems (for example, uninterruptable power system and generator backup subsystem). • Communicates and Reviews Detected Environmental Threat Events — Detected environmental threat events are communicated to and reviewed by the individuals responsible for the management of the system, and actions are taken, if necessary. • Determines Data Requiring Backup — Data is evaluated to determine whether backup is required. • Performs Data Backup — Procedures are in place for backing up data, monitoring to detect backup failures, and initiating corrective action when such failures occur. • Addresses Offsite Storage — Backup data is stored in a location at a distance from its principal storage location sufficient that the likelihood of a security or environmental threat event affecting both sets of data is reduced to an appropriate level. • Implements Alternate Processing Infrastructure — Measures are implemented for migrating processing to alternate infrastructure in the event normal processing infrastructure becomes unavailable. Measures may include geographic separation, redundancy, and failover capabilities for components.  • Considers Data Recoverability — Management identifies threats to data recoverability (for example, ransomware attacks) that could impair the availability of the system and related data and implements mitigation procedures. 
', NULL),
('A1.3', 'Availability', 'A1 - Availability', 'The entity tests recovery plan procedures supporting system recovery to meet its objectives.', '• Implements Business Continuity Plan Testing — Business continuity plan testing is performed on a periodic basis to test the entity’s ability to respond to, recover from, and resume operations through significant disruptions. Testing includes (1) development of testing scenarios based on threat likelihood and magnitude; (2) consideration of system components from across the entity and vendors that can impair availability; (3) scenarios that consider the potential for the lack of availability of • Implements Business Continuity Plan Testing — Business continuity plan testing is performed on a periodic basis to test the entity’s ability to respond to, recover from, and resume operations through significant disruptions. Testing includes (1) development of testing scenarios based on threat likelihood and magnitude; (2) consideration of system components from across the entity and vendors that can impair availability; (3) scenarios that consider the potential for the lack of availability of key personnel or vendors; and (4) revision of continuity plans and systems based on test results. 
• Tests Integrity and Completeness of Backup Data — The integrity and completeness of backup information is tested on a periodic basis. 

', NULL),
('C1.1', 'Confidentiality', 'C1 - Confidentiality', 'The entity identifies and maintains confidential information to meet the entity’s objectives related to confidentiality.', '• Defines and Identifies Confidential information — Procedures are in place to define, identify, and designate confidential information when it is received or created.  • Retains Confidential Information — Confidential information is retained for no longer than necessary to fulfill the identified purpose, unless a law or regulation specifically requires otherwise. • Protects Confidential Information From Destruction — Policies and procedures are in place to protect confidential information from erasure or destruction during the specified retention period of the information. 
', NULL),
('C1.2', 'Confidentiality', 'C1 - Confidentiality', 'The entity disposes of confidential information to meet the entity’s objectives related to confidentiality.', '• Identifies Confidential Information for Destruction — Procedures are in place to identify confidential information requiring destruction when the end of the retention period is reached. • Destroys Confidential Information — Policies and procedures are in place to automatically or manually erase or otherwise destroy confidential information that has been identified for destruction. 
', NULL),
('CC1.1', 'Common', '1.0 – Control Environment', 'The entity demonstrates a commitment to integrity and ethical values.', '- **Sets the Tone at the Top:** The board of directors and management, at all levels, demonstrate through their directives, actions, and behavior the importance of integrity and ethical values to support the functioning of the system of internal control.
- **Establishes Standards of Conduct:** The expectations of the board of directors and senior management concerning integrity and ethical values are defined in the entity’s standards of conduct and understood at all levels of the entity and by outsourced service providers and business partners.
- **Evaluates Adherence to Standards of Conduct:** Processes are in place to evaluate the performance of individuals and teams against the entity’s expected standards of conduct.
- **Addresses Deviations in a Timely Manner:** Deviations from the entity’s expected standards of conduct are identified and remedied in a timely and consistent manner.

', '**Considers Contractors and Vendor Employees in Demonstrating Its Commitment:** Management and the board of directors consider the use of contractors and vendor employees in its processes for establishing standards of conduct, evaluating adherence to those standards, and addressing deviations in a timely manner.
'),
('CC1.2', 'Common', '1.0 – Control Environment', 'The board of directors demonstrates independence from management and exercises oversight of the development and performance of internal control.', '- **Establishes Oversight Responsibilities:** The board identifies and accepts its oversight responsibilities regarding established requirements and expectations.
- **Applies Relevant Expertise:** The board defines and periodically evaluates the skills and expertise needed among members to ensure they can effectively challenge senior management.
- **Operates Independently:** The board maintains enough members who are independent of management to remain objective in evaluations and decision-making.

', '- **Supplements Board Expertise:** The board brings in additional expertise related to **security, availability, processing integrity, confidentiality, and privacy** via subcommittees or external consultants as needed.

'),
('CC1.3', 'Common', '1.0 – Control Environment', 'Management establishes, with board oversight, structures, reporting lines, and appropriate authorities and responsibilities in the pursuit of objectives.', '• Considers All Structures of the Entity — Management and the board of directors consider the multiple structures used (including operating units, legal entities, geographic distribution, and outsourced service providers) to support the achievement of objectives.  • Establishes Reporting Lines — Management designs and evaluates lines of reporting for each entity structure to enable execution of authorities and responsibilities and flow of information to manage the activities of the entity.  • Defines, Assigns, and Limits Authorities and Responsibilities — Management and the board of directors delegate authority, define responsibilities, and use appropriate processes and technology to assign responsibility and segregate duties as necessary at the various levels of the organization. 
', '• Addresses Specific Requirements When Defining Authorities and Responsibilities — Management and the board of directors consider requirements relevant to security, availability, processing integrity, confidentiality, and privacy when defining authorities and responsibilities.  • Considers Interactions With External Parties When Establishing Structures, Reporting Lines, Authorities, and Responsibilities — Management and the board of directors consider the need for the entity to interact with and monitor the activities of external parties when establishing structures, reporting lines, authorities, and responsibilities. 
'),
('CC1.4', 'Common', '1.0 – Control Environment', 'The entity demonstrates a commitment to attract, develop, and retain competent individuals in alignment with objectives.', '• Establishes Policies and Practices — Policies and practices reflect expectations of competence necessary to support the achievement of objectives. • Evaluates Competence and Addresses Shortcomings — The board of directors and management evaluate competence across the entity and in outsourced service providers in relation to established policies and practices and act as necessary to address shortcomings. • Attracts, Develops, and Retains Individuals — The entity provides the mentoring and training needed to attract, develop, and retain sufficient and competent personnel and outsourced service providers to support the achievement of objectives. • Plans and Prepares for Succession — Senior management and the board of directors develop contingency plans for assignments of responsibility important for internal control. 
', '• Considers the Background of Individuals — The entity considers the background of potential and existing personnel, contractors, and vendor employees when determining whether to employ and retain the individuals. • Considers the Technical Competency of Individuals — The entity considers the technical competency of potential and existing personnel, contractors, and vendor employees when determining whether to employ and retain the individuals. • Provides Training to Maintain Technical Competencies — The entity provides training programs, including continuing education and training, to ensure skill sets and technical competency of existing personnel, contractors, and vendor employees are developed and maintained. 
'),
('CC1.5', 'Common', '1.0 – Control Environment', 'The entity holds individuals accountable for their internal control responsibilities in the pursuit of objectives.', '- **Enforces Accountability Through Structures, Authorities, and Responsibilities** — Management and the board of directors establish the mechanisms to communicate and hold individuals accountable for performance of internal control responsibilities across the entity and implement corrective action as necessary.
- **Establishes Performance Measures, Incentives, and Rewards** — Management and the board of directors establish performance measures, incentives, and other rewards appropriate for responsibilities at all levels of the entity, reflecting appropriate dimensions of performance and expected standards of conduct, and considering the achievement of both short-term and longer-term objectives.
- **Evaluates Performance Measures, Incentives, and Rewards for Ongoing Relevance** — Management and the board of directors align incentives and rewards with the fulfillment of internal control responsibilities in the achievement of objectives.
- **Considers Excessive Pressures** — Management and the board of directors evaluate and adjust pressures associated with the achievement of objectives as they assign responsibilities, develop performance measures, and evaluate performance.
- **Evaluates Performance and Rewards or Disciplines Individuals** — Management and the board of directors evaluate performance of internal control responsibilities, including adherence to standards of conduct and expected levels of competence, and provide rewards or exercise disciplinary action, as appropriate.


', '**Takes Disciplinary Actions** — A sanctions process is defined, and applied as needed, when an employee violates the entity’s privacy policies or when an employee’s negligent behavior causes a privacy incident.
'),
('CC2.1', 'Common', '2.0 – Information and Communication', 'The entity obtains or generates and uses relevant, quality information to support the functioning of internal control.', 'These points address the foundational organizational structure and delegation of power:
- **Considers All Structures of the Entity:** Management and the board evaluate the various structures used—such as operating units, legal entities, geographic distribution, and outsourced providers—to support organizational objectives.
- **Establishes Reporting Lines:** Management creates and assesses lines of reporting for every entity structure to ensure authorities are executed and information flows properly to manage entity activities.
- **Defines, Assigns, and Limits Authorities and Responsibilities:** Management and the board delegate authority and define responsibilities using processes and technology to assign tasks and segregate duties across the organization.

', '### Additional Points of Focus (Trust Services Criteria)
These points apply when the trust services criteria are being utilized:
- **Addresses Specific Requirements When Defining Authorities and Responsibilities:** Management and the board incorporate requirements for security, availability, processing integrity, confidentiality, and privacy when establishing authorities.
- **Considers Interactions With External Parties When Establishing Structures, Reporting Lines, Authorities, and Responsibilities:** Management and the board account for the need to interact with and monitor external parties'' activities during the setup of organizational structures and responsibilities.

### Additional Point of Focus (Trust Services Criteria for Privacy)
This point specifically applies to privacy-related compliance:
- **Establishes Structures, Reporting Lines, and Authorities to Support Compliance With Legal and Contractual Privacy Requirements:** When setting up structures and authorities, management ensures they align with legal and contractual privacy objectives and requirements.
- 

'),
('CC2.2', 'Common', '2.0 – Information and Communication', 'The entity internally communicates information, including objectives and responsibilities for internal control, necessary to support the functioning of internal control.', '• Communicates Internal Control Information — A process is in place to communicate required information to enable all personnel to understand and carry out their internal control responsibilities. • Communicates With the Board of Directors — Communication exists between management and the board of directors so that both have information needed to fulfill their roles with respect to the entity’s objectives. • Provides Separate Communication Lines — Separate communication channels, such as whistle-blower hotlines, are in place and serve as fail-safe mechanisms to enable anonymous or confidential communication when normal channels are inoperative or ineffective. • Selects Relevant Method of Communication — The method of communication considers the timing, audience, and nature of the information. 
', '• Communicates Responsibilities — Entity personnel with responsibility for designing, developing, implementing, operating, maintaining, or monitoring system controls receive communications about their responsibilities, including changes in their responsibilities, and have the information necessary to carry out those responsibilities. 
• Communicates Information on Reporting Failures, Incidents, Concerns, and Other Matters — Entity personnel are provided with information on how to report systems failures, incidents, concerns, and other complaints. • Communicates Objectives and Changes to Objectives — The entity communicates its objectives and changes to those objectives to personnel in a timely manner. • Communicates Information to Improve Security Knowledge and Awareness — The entity communicates information to improve security knowledge and awareness and to model appropriate security behaviors to personnel through a security awareness training program. 
• Communicates Information to Improve Privacy Knowledge and Awareness — The entity communicates information to improve privacy knowledge and awareness and to model appropriate behaviors to personnel through a privacy awareness training program. • Communicates Incident Reporting Methods — The entity has communicated to employees and others within the entity the process used to report a suspected privacy incident.  
'),
('CC2.3', 'Common', '2.0 – Information and Communication', 'The entity communicates with external parties regarding matters affecting the functioning of internal control.', '• Communicates to External Parties — Processes are in place to communicate relevant and timely information to external parties, including shareholders, partners, owners, regulators, customers, financial analysts, and other external parties. • Enables Inbound Communications — Open communication channels allow input from customers, consumers, suppliers, external auditors, regulators, financial analysts, and others, providing management and the board of directors with relevant information. • Communicates With the Board of Directors — Relevant information resulting from assessments conducted by external parties is communicated to the board of directors. • Provides Separate Communication Lines — Separate communication channels, such as whistle-blower hotlines, are in place and serve as fail-safe mechanisms to enable anonymous or confidential communication when normal channels are inoperative or ineffective. • Selects Relevant Method of Communication — The method of communication considers the timing, audience, and nature of the communication and legal, regulatory, and fiduciary requirements and expectations. 
', '• Communicates Objectives Related to Confidentiality and Changes to Those Objectives — The entity communicates, to external users, vendors, business partners, and others whose products or services, or both, are part of the system, the entity’s objectives related to confidentiality and the protection of confidential information, as well as changes to those objectives. 
• Communicates Objectives Related to Privacy and Changes to Those Objectives — The entity communicates, to external users, vendors, business partners, and others whose products or services, or both, are part of the system, the entity’s objectives related to privacy and the protection of personal information, as well as changes to those objectives.  • Communicates Incident Reporting Methods — The entity communicates to user entities, third parties, data subjects, and others the process used to report a suspected privacy incident.  
'),
('CC3.1', 'Common', '3.0 – Common Criteria Related to Risk Assessment', 'The entity specifies objectives with sufficient clarity to enable the identification and assessment of risks relating to objectives.', '**Points of focus specified in the COSO framework: **
    **Operations Objectives **fn 16 
• Reflects Management''s Choices — Operations objectives reflect management''s choices about structure, industry considerations, and performance of the entity. 
     • Considers Tolerances for Risk — Management considers the acceptable levels of variation relative to the achievement of operations objectives. 
     • Includes Operations and Financial Performance Goals — The organization reflects the desired level of operations and financial performance for the entity within opera- tions objectives. 
     • Forms a Basis for Committing of Resources — Management uses operations objec- tives as a basis for allocating resources needed to attain desired operations and fi- nancial performance. 
     **External Financial Reporting Objectives **fn 17 
• Complies With Applicable Accounting Standards — Financial reporting objectives are consistent with accounting principles suitable and available for that entity. The accounting principles selected are appropriate in the circumstances. 
     • Considers Materiality — Management considers materiality in financial statement presentation. 
     • Reflects Entity Activities — External reporting reflects the underlying transactions and events to show qualitative characteristics and assertions. 
      **External Nonfinancial Reporting Objectives **fn 18 
• Complies With Externally Established Frameworks — Management establishes ob- jectives consistent with laws and regulations or standards and frameworks of recog- nized external organizations. 
     • Considers the Required Level of Precision — Management reflects the required level of precision and accuracy suitable for user needs and based on criteria estab- lished by third parties in nonfinancial reporting. 
     • Reflects Entity Activities — External reporting reflects the underlying transactions and events within a range of acceptable limits. 
     **Internal Reporting Objectives **fn 19 
• Reflects Management''s Choices — Internal reporting provides management with accurate and complete information regarding management''s choices and information needed in managing the entity. 
     • Considers the Required Level of Precision — Management reflects the required level of precision and accuracy suitable for user needs in nonfinancial reporting ob- jectives and materiality within financial reporting objectives. 
     • Reflects Entity Activities — Internal reporting reflects the underlying transactions and events within a range of acceptable limits. 
     **Compliance Objectives **fn 20 
• Reflects External Laws and Regulations — Laws and regulations establish mini- mum standards of conduct, which the entity integrates into compliance objectives. 
     • Considers Tolerances for Risk — Management considers the acceptable levels of variation relative to the achievement of operations objectives. 
  
', ' _Establishes Sub-Objectives for Risk Assessment — Management identifies sub-ob- jectives for use in risk assessment related to security, availability, processing integ- rity, confidentiality, or privacy to support the achievement of the entity’s objectives. _
'),
('CC3.2', 'Common', '3.0 – Common Criteria Related to Risk Assessment', 'The entity identifies risks to the achievement of its objectives across the entity and analyzes risks as a basis for determining how the risks should be managed.', '    Includes Entity, Subsidiary, Division, Operating Unit, and Functional Levels — The entity identifies and assesses risk at the entity, subsidiary, division, operating unit, and functional levels relevant to the achievement of objectives. 
     • Analyzes Internal and External Factors _— _Risk identification considers both internal and external factors and their impact on the achievement of objectives. 
     • Involves Appropriate Levels of Management _— _The entity puts into place effective risk assessment mechanisms that involve appropriate levels of management. 
     • Estimates Significance of Risks Identified _— _Identified risks are analyzed through a process that includes estimating the potential significance of the risk. 
     • Determines How to Respond to Risks — Risk assessment includes considering how the risk should be managed and whether to accept, avoid, reduce, or share the risk. 
  
', '_Identifies Threats to Objectives — The entity identifies threats to the achievement of its objectives from intentional (including malicious) and unintentional acts and en- vironmental events. _
    _Identifies Vulnerability of System Components _— _The entity identifies the vulnera- bilities of system components, including system processes, infrastructure, software, and other information assets. _
     • _Analyzes Threats and Vulnerabilities From Vendors, Business Partners, and Other Parties — The entity''s risk assessment process includes the analysis of potential threats and vulnerabilities arising from vendors providing goods and services, as well as threats and vulnerabilities arising from business partners, customers, and other third parties with access to the entity''s information systems. _
     • _Assesses the Significance of the Risks — The entity assesses the significance of the identified risks, including (1) determining the criticality of system components, in- cluding information assets, in achieving the objectives; (2) assessing the susceptibil- ity of the identified vulnerabilities to the identified threats; (3) assessing the likeli- hood of the identified risks; (4) assessing the magnitude of the effect of potential risks to the achievement of the objectives; (5) considering the potential effects of un- identified threats and vulnerabilities on the assessed risks; (6) developing risk miti- gation strategies to address the assessed risks; and (7) evaluating the appropriate- ness of residual risk (including whether to accept, reduce, or share such risks). _
  
'),
('CC3.3', 'Common', '3.0 – Common Criteria Related to Risk Assessment', 'The entity considers the potential for fraud in assessing risks to the achievement of objectives.', '• Considers Various Types of Fraud — The assessment of fraud considers fraudulent reporting, possible loss of assets, and corruption resulting from the various ways that fraud and misconduct can occur. 
• Assesses Incentives and Pressures — The assessment of fraud risks considers incentives and pressures. 
• Assesses Opportunities — The assessment of fraud risk considers opportunities for unauthorized acquisition, use, or disposal of assets, altering the entity’s reporting records, or committing other inappropriate acts. 
• Assesses Attitudes and Rationalizations — The assessment of fraud risk considers how management and other personnel might engage in or justify inappropriate actions. 
', 'Considers the Risks Related to the Use of IT and Access to Information — The assessment of fraud risks includes consideration of internal and external threats and vulnerabilities that arise specifically from the use of IT and access to information. 
'),
('CC3.4', 'Common', '3.0 – Common Criteria Related to Risk Assessment', 'The entity identifies and assesses changes that could significantly impact the system of internal control.', '• Assesses Changes in the External Environment — The risk identification process considers changes to the regulatory, economic, and physical environment in which the entity operates.  • Assesses Changes in the Business Model — The entity considers the potential impacts of new business lines, dramatically altered compositions of existing business lines, acquired or divested business operations on the system of internal control, rapid growth, changing reliance on foreign geographies, and new technologies.  • Assesses Changes in Leadership — The entity considers changes in management and respective attitudes and philosophies on the system of internal control. 
', '• Assesses Changes in Systems and Technology — The risk identification process considers changes arising from changes in the entity’s systems and changes in the technology environment.  • Assesses Changes in Vendor and Business Partner Relationships — The risk identification process considers changes in vendor and business partner relationships.  • Assesses Changes in Threats and Vulnerabilities — The risk identification process assesses changes in (1) internal and external threats to and vulnerabilities of the components of the entity’s systems and (2) the likelihood and magnitude of the resultant risks to the achievement of the entity’s objectives. 
'),
('CC4.1', 'Common', '4.0 – Common Criteria Related to Monitoring Activities', 'The entity selects, develops, and performs ongoing and/or separate evaluations to ascertain whether the components of internal control are present and functioning.', 'Considers a Mix of Ongoing and Separate Evaluations — Management includes a balance of ongoing and separate evaluations.  • Considers Rate of Change — Management considers the rate of change in business and business processes when selecting and developing ongoing and separate evaluations.  • Establishes Baseline Understanding — The design and current state of an internal control system are used to establish a baseline for ongoing and separate evaluations.  • Uses Knowledgeable Personnel — Evaluators performing ongoing and separate evaluations have sufficient knowledge to understand what is being evaluated.  • Integrates With Business Processes — Ongoing evaluations are built into the business processes and adjust to changing conditions. 
• Adjusts Scope and Frequency — Management varies the scope and frequency of separate evaluations depending on risk. • Objectively Evaluates — Separate evaluations are performed periodically to provide objective feedback. 	
', '• Considers Different Types of Ongoing and Separate Evaluations — Management uses a variety of ongoing and separate risk and control evaluations to determine whether internal controls are present and functioning. Depending on the entity’s objectives, such risk and control evaluations may include first- and second-line monitoring and control testing, internal audit assessments, compliance assessments, resilience assessments, vulnerability scans, security assessment, penetration testing, and third-party assessments. 
'),
('CC4.2', 'Common', '4.0 – Common Criteria Related to Monitoring Activities', 'The entity evaluates and communicates internal control deficiencies in a timely manner to those parties responsible for taking corrective action, including senior management and the board of directors, as appropriate', '• Assesses Results — Management and the board of directors, as appropriate, assess results of ongoing and separate evaluations. • Communicates Deficiencies — Deficiencies are communicated to parties responsible for taking corrective action and to senior management and the board of directors, as appropriate. • Monitors Corrective Action — Management tracks whether deficiencies are remedied on a timely basis. 
', NULL),
('CC5.1', 'Common', '5.0 – Common Criteria Related to Control Activities', 'The entity selects and develops control activities that contribute to the mitigation of risks to the achievement of objectives to acceptable levels.', '• Integrates With Risk Assessment — Control activities help ensure that risk responses that address and mitigate risks are carried out. • Considers Entity-Specific Factors — Management considers how the environment, complexity, nature, and scope of its operations, as well as the specific characteristics of its organization, affect the selection and development of control activities. • Determines Relevant Business Processes — Management determines which relevant business processes require control activities. • Evaluates a Mix of Control Activity Types — Control activities include a range and variety of controls and may include a balance of approaches to mitigate risks, considering both manual and automated controls, and preventive and detective controls. • Considers at What Level Activities Are Applied — Management considers control activities at various levels in the entity. • Addresses Segregation of Duties — Management segregates incompatible duties and, where such segregation is not practical, management selects and develops alternative control activities. 
', NULL),
('CC5.2', 'Common', '5.0 – Common Criteria Related to Control Activities', 'The entity also selects and develops general control activities over technology to support the achievement of objectives.', '• Determines Dependency Between the Use of Technology in Business Processes and Technology General Controls — Management understands and determines the dependency and linkage between business processes, automated control activities, and technology general controls. • Establishes Relevant Technology Infrastructure Control Activities — Management selects and develops control activities over the technology infrastructure, which are designed and implemented to help ensure the completeness, accuracy, and availability of technology processing. • Establishes Relevant Security Management Process Controls Activities — Management selects and develops control activities that are designed and implemented to restrict technology access rights to authorized users commensurate with their job responsibilities and to protect the entity’s assets from external threats. • Establishes Relevant Technology Acquisition, Development, and Maintenance Process Control Activities — Management selects and develops control activities over the acquisition, development, and maintenance of technology and its infrastructure to achieve management’s objectives. 
', NULL),
('CC5.3', 'Common', '5.0 – Common Criteria Related to Control Activities', 'The entity deploys control activities through policies that establish what is expected and in procedures that put policies into action.', '• Establishes Policies and Procedures to Support Deployment of Management’s Directives — Management establishes control activities that are built into business processes and employees’ day-to-day activities through policies establishing what is expected and relevant procedures specifying actions. • Establishes Responsibility and Accountability for Executing Policies and Procedures — Management establishes responsibility and accountability for control activities with management (or other designated personnel) of the business unit or function in which the relevant risks reside. • Performs in a Timely Manner — Responsible personnel perform control activities in a timely manner as defined by the policies and procedures. • Takes Corrective Action — Responsible personnel investigate and act on matters identified as a result of executing control activities. • Performs Using Competent Personnel — Competent personnel with sufficient authority perform control activities with diligence and continuing focus. 
• Reassesses Policies and Procedures — Management periodically reviews control activities to determine their continued relevance and refreshes them when necessary. 
', NULL),
('CC6.1', 'Common', '6.0 – Common Criteria Related to Logical and Physical Access', 'The entity implements logical access security software, infrastructure, and architectures over protected information assets to protect them from security events to meet the entity''s objectives.', '• Identifies and Manages the Inventory of Information Assets — The entity identifies, inventories, classifies, and manages information assets (for example, infrastructure, software, and data). • Assesses New Architectures — The entity identifies new system architectures and assesses their security prior to implementation into the system environment. • Restricts Logical Access — The entity restricts logical access to information assets, including infrastructure (for example, server, storage, network elements, APIs, and endpoint devices), software, and data (at rest, during processing, or in transmission) through the use of access control software, rule sets, and standard configuration hardening processes. • Identifies and Authenticates Users — The entity identifies and authenticates persons, infrastructure, and software prior to accessing information assets, whether locally or remotely. The entity uses more complex or advanced user authentication techniques such as multifactor authentication when such protections are deemed appropriate based on its risk mitigation strategy. • Considers Network Segmentation — The entity uses network segmentation, zero trust architectures, and other techniques to isolate unrelated portions of the entity''s information technology from each other based on the entity’s risk mitigation strategy. • Manages Points of Access — Points of access by outside entities and the types of data that flow through the points of access are identified, inventoried, and managed. The types of individuals and systems using each point of access are identified, documented, and managed. 
• Restricts Access to Information Assets — Combinations of data classification, separate data structures, port restrictions, access protocol restrictions, user identification, and digital certificates are used to establish access control rules and configuration standards for information assets. • Manages Identification and Authentication — Identification and authentication requirements are established, documented, and managed for individuals and systems accessing entity information, infrastructure, and software. • Manages Credentials for Infrastructure and Software — New internal and external infrastructure and software are registered, authorized, and documented prior to being granted access credentials and implemented on the network or access point. Credentials are removed and access is disabled when access is no longer required or the infrastructure and software are no longer in use. • Uses Encryption to Protect Data — The entity uses encryption to protect data (at rest, during processing, or in transmission), when such protections are deemed appropriate based on the entity’s risk mitigation strategy. • Protects Cryptographic Keys — The entity protects cryptographic keys during generation, storage, use, and destruction. Cryptographic modules, algorithms, key lengths, and architectures are appropriate based on the entity’s risk mitigation strategy. 	
', '• Restricts Access to and the Use of Personal Information — Logical access to and use of personal information is restricted to authorized personnel who require such access to fulfill the identified purposes to support the achievement of the entity’s objectives related to privacy.  
'),
('CC6.2', 'Common', '6.0 – Common Criteria Related to Logical and Physical Access', 'Prior to issuing system credentials and granting system access, the entity registers and authorizes new internal and external users whose access is administered by the entity. For those users whose access is administered by the entity, user system credentials are removed when user access is no longer authorized.', '• Creates Access Credentials to Protected Information Assets — The entity creates credentials for accessing protected information assets based on an authorization from the system''s asset owner or authorized custodian. Authorization is required for the creation of all types of credentials of individuals (for example, employees, contractors, vendors, and business partner personnel), systems, and software. • Reviews Validity of Access Credentials — The entity reviews access credentials on a periodic basis for validity (for example, employees, contractors, vendors, and business partner personnel) and inappropriate system or service accounts.  • Prevents the Use of Credentials When No Longer Valid — Processes are in place to disable, destroy, or otherwise prevent the use of access credentials when no longer valid. 
', NULL),
('CC6.3', 'Common', '6.0 – Common Criteria Related to Logical and Physical Access', 'The entity authorizes, modifies, or removes access to data, software, functions, and other protected information assets based on roles, responsibilities, or the system design and changes, giving consideration to the concepts of least privilege and segregation of duties, to meet the entity’s objectives', '• Creates or Modifies Access to Protected Information Assets — Processes are in place to create or modify access to protected information assets based on authorization from the asset’s owner. • Removes Access to Protected Information Assets — Processes are in place to remove access to protected information assets when no longer required. 
• Uses Access Control Structures — The entity uses access control structures, such as role-based access controls, to restrict access to protected information assets, limit privileges, and support segregation of incompatible functions. • Reviews Access Roles and Rules — The appropriateness of access roles and access rules is reviewed on a periodic basis for unnecessary and inappropriate individuals (for example, employees, contractors, vendors, business partner personnel) and inappropriate system or service accounts. Access roles and rules are modified, as appropriate. 
', NULL),
('CC6.4', 'Common', '6.0 – Common Criteria Related to Logical and Physical Access', 'The entity restricts physical access to facilities and protected information assets (for example, data center facilities, back-up media storage, and other sensitive locations) to authorized personnel to meet the entity’s objectives.', '• Creates or Modifies Physical Access — Processes are in place to create or modify physical access by employees, contractors, vendors, and business partner personnel to facilities such as data centers, office spaces, and work areas, based on appropriate authorization.  • Removes Physical Access — Processes are in place to remove physical access to facilities and protected information assets when an employee, contractor, vendor, or business partner no longer requires access.  • Recovers Physical Devices — Processes are in place to recover entity devices (for example, badges, laptops, and mobile devices) when an employee, contractor, vendor, or business partner no longer requires access.  • Reviews Physical Access — Processes are in place to periodically review physical access to help ensure consistency with job responsibilities. 
', NULL),
('CC6.5', 'Common', '6.0 – Common Criteria Related to Logical and Physical Access', 'The entity discontinues logical and physical protections over physical assets only after the ability to read or recover data and software from those assets has been diminished and is no longer required to meet the entity’s objectives.', '• Removes Data and Software for Disposal — Procedures are in place to remove, delete, or otherwise render data and software inaccessible from physical assets and other devices owned by the entity, its vendors, and employees when the data and software are no longer required on the asset or the asset will no longer be under the control of the entity.  
', NULL),
('CC6.6', 'Common', '6.0 – Common Criteria Related to Logical and Physical Access', 'The entity implements logical access security measures to protect against threats from sources outside its system boundaries.', '• Restricts Access — The types of activities that can occur through a communication channel (for example, FTP site, router port) are restricted. • Protects Identification and Authentication Credentials — Identification and authentication credentials are protected during transmission outside its system boundaries. • Requires Additional Authentication or Credentials — Additional authentication information or credentials are required when accessing the system from outside its boundaries. • Implements Boundary Protection Systems — Boundary protection systems (for example, firewalls, demilitarized zones, intrusion detection or prevention systems, and endpoint detection and response systems) are configured, implemented, and maintained to protect external access points.  
', NULL),
('CC6.7', 'Common', '6.0 – Common Criteria Related to Logical and Physical Access', 'The entity restricts the transmission, movement, and removal of information to authorized internal and external users and processes, and protects it during transmission, movement, or removal to meet the entity’s objectives.', '• Restricts the Ability to Perform Transmission — Data loss prevention processes and technologies are used to restrict ability to authorize and execute transmission, movement, and removal of information. 
• Uses Encryption Technologies or Secure Communication Channels to Protect Data — Encryption technologies or secured communication channels are used to protect transmission of data and other communications beyond connectivity access points. • Protects Removal Media — Encryption technologies and physical asset protections are used for removable media (such as USB drives and backup tapes), as appropriate. • Protects Endpoint Devices — Processes and controls are in place to protect endpoint devices (such as mobile devices, laptops, desktops, and sensors). 
', NULL),
('CC6.8', 'Common', '6.0 – Common Criteria Related to Logical and Physical Access', 'The entity implements controls to prevent or detect and act upon the introduction of unauthorized or malicious software to meet the entity’s objectives.', '• Restricts Installation and Modification of Application and Software — The ability to install and modify applications and software is restricted to authorized individuals. Utility software capable of bypassing normal operating or security procedures is limited to use by authorized individuals and is monitored regularly. • Detects Unauthorized Changes to Software and Configuration Parameters — Processes are in place to detect changes to software and configuration parameters that may be indicative of unauthorized or malicious software. • Uses a Defined Change Control Process — A management-defined change control process is used for the implementation of software. • Uses Antivirus and Anti-Malware Software — Antivirus and anti-malware software on servers and endpoint devices is configured, implemented, and maintained to provide for the interception or detection and remediation of malware.  • Scans Information Assets From Outside the Entity for Malware and Other Unauthorized Software — Procedures are in place to scan information assets that have been transferred or returned to the entity’s custody for malware and other unauthorized software. Detected malware or other software is removed prior to connection to the entity’s network. 

', NULL),
('CC7.1', 'Common', '7.0 – Common Criteria Related to System Operations', 'To meet its objectives, the entity uses detection and monitoring procedures to identify (1) changes to configurations that result in the introduction of new vulnerabilities, and (2) susceptibilities to newly discovered vulnerabilities.', '• Uses Defined Configuration Standards — The entity has defined configuration standards to be used for hardening systems. • Monitors Infrastructure and Software — The entity monitors infrastructure and software for noncompliance with the standards, which could threaten the achievement of the entity''s objectives. • Implements Change-Detection Mechanisms — The IT system includes a change-detection mechanism (for example, file integrity monitoring tools) to alert personnel to unauthorized modifications of critical system files, configuration files, or content files. • Detects Unknown or Unauthorized Components — Procedures are in place to detect the introduction of unknown or unauthorized components. • Conducts Vulnerability Scans — The entity conducts infrastructure and software vulnerability scans designed to identify potential vulnerabilities or misconfigurations on a periodic basis and after significant changes are made to the environment. Action is taken to remediate identified deficiencies in a timely manner to support the achievement of the entity’s objectives. 
', NULL),
('CC7.2', 'Common', '7.0 – Common Criteria Related to System Operations', 'The entity monitors system components and the operation of those components for anomalies that are indicative of malicious acts, natural disasters, and errors affecting the entity''s ability to meet its objectives; anomalies are analyzed to determine whether they represent security events.', '• Implements Detection Policies, Procedures, and Tools — Detection policies, procedures, and tools are defined and implemented on infrastructure and software to identify potential intrusions, inappropriate access, and anomalies in the operation of or unusual activity on systems. Procedures may include (1) a defined governance process for security event detection and management; (2) use of intelligence sources to identify newly discovered threats and vulnerabilities; and (3) logging of unusual system activities. • Designs Detection Measures — Detection measures are designed to identify anomalies that could result from actual or attempted (1) compromise of physical barriers; (2) unauthorized actions of authorized personnel; (3) use of compromised identification and authentication credentials; (4) unauthorized access from outside the system boundaries; (5) compromise of authorized external parties; and (6) implementation or connection of unauthorized hardware and software. • Implements Filters to Analyze Anomalies — Management has implemented procedures to filter, summarize, and analyze anomalies to identify security events. • Monitors Detection Tools for Effective Operation — Management has implemented processes to monitor and maintain the effectiveness of detection tools. 
', NULL),
('CC7.3', 'Common', '7.0 – Common Criteria Related to System Operations', 'The entity evaluates security events to determine whether they could or have resulted in a failure of the entity to meet its objectives (security incidents) and, if so, takes actions to prevent or address such failures.', '• Responds to Security Incidents — Procedures are in place for responding to security incidents and evaluating the effectiveness of those policies and procedures on a periodic basis. • Communicates and Reviews Detected Security Events — Detected security events are communicated to and reviewed by the individuals responsible for the management of the security program, and actions are taken, if necessary. • Develops and Implements Procedures to Analyze Security Incidents — Procedures are in place to analyze security incidents and determine system impact.
', '• Assesses the Impact on Confidential Information — Detected security events are evaluated to determine whether they could or did result in the unauthorized disclosure or use of confidential information. • Determines Confidential Information Used or Disclosed — When an unauthorized use or disclosure of confidential information has occurred, the affected information is identified and actions are taken to help prevent future recurrence and address control failures to support the achievement of entity objectives. 
• Assesses the Impact on Personal Information — Detected security events are evaluated to determine whether they could or did result in the unauthorized disclosure or use of personal information and whether there has been a failure to comply with applicable laws or regulations. • Determines Personal Information Used or Disclosed — When an unauthorized use or disclosure of personal information has occurred, the affected information is identified and actions are taken to help prevent future recurrence and address control failures to support the achievement of entity objectives. 
'),
('CC7.4', 'Common', '7.0 – Common Criteria Related to System Operations', 'The entity responds to identified security incidents by executing a defined incident response program to understand, contain, remediate, and communicate security incidents, as appropriate.', '• Assigns Roles and Responsibilities — Roles and responsibilities for the design, implementation, maintenance, and execution of the incident-response program are assigned, including the use of external resources when necessary. • Contains and Responds to Security Incidents — Procedures are in place to respond to and contain security incidents that actively threaten entity objectives. 
• Mitigates Ongoing Security Incidents — Procedures are in place to mitigate the effects of ongoing security incidents. • Resolves Security Incidents — Procedures are in place to resolve security incidents through closure of vulnerabilities, removal of unauthorized access, and other remediation actions. • Restores Operations — Procedures are in place to restore data and business operations to an interim state that permits the achievement of entity objectives. • Develops and Implements Communication of Security Incidents — Protocols for communicating, in a timely manner, information regarding security incidents and actions taken to affected parties are developed and implemented to support the achievement of the entity''s objectives. • Obtains Understanding of Nature of Incident and Determines Containment Strategy — An understanding of the nature (for example, the method by which the incident occurred and the affected system resources) and severity of the security incident is obtained to determine the appropriate response and containment strategy, including (1) a determination of the appropriate response time frame, and (2) the determination and execution of the containment approach. • Remediates Identified Vulnerabilities — Identified vulnerabilities are remediated through the development and execution of remediation activities. • Communicates Remediation Activities — Remediation activities are documented and communicated in accordance with the incident-response program. • Evaluates the Effectiveness of Incident Response — The design of incident-response activities is evaluated for effectiveness on a periodic basis. • Periodically Evaluates Incidents — Periodically, management reviews incidents related to security, availability, processing integrity, confidentiality, and privacy and identifies the need for system changes based on incident patterns and root causes. 
', '• Applies Breach Response Procedures — Breach response procedures are defined and applied in the event of a confirmed privacy incident.  • Communicates Unauthorized Use and Disclosure — Events that resulted in unauthorized use or disclosure of personal information are communicated to the data subjects, legal and regulatory authorities, and others as required. • Application of Sanctions — The conduct of individuals and organizations operating under the authority of the entity and involved in the unauthorized use or disclosure of personal information is evaluated and, if appropriate, sanctioned in accordance with entity policies and legal and regulatory requirements. 
'),
('CC7.5', 'Common', '7.0 – Common Criteria Related to System Operations', 'The entity identifies, develops, and implements activities to recover from identified security incidents.', '• Restores the Affected Environment — The activities restore the affected environment to functional operation by rebuilding systems, updating software, installing patches, modifying access controls, and changing configurations, as needed. • Communicates Information About the Incident — Communications about the nature of the incident, recovery actions taken, and activities required for the prevention of future security incidents are made to management and others as appropriate (internal and external). • Determines Root Cause of the Incident — The root cause of the incident is determined. • Implements Changes to Prevent and Detect Recurrences — Additional architecture or changes to preventive and detective controls are implemented to prevent and detect incident recurrences in a timely manner. • Improves Response and Recovery Procedures — Lessons learned are analyzed and the incident-response plan and recovery procedures are improved. • Implements Incident-Recovery Plan Testing — Incident-recovery plan testing is performed on a periodic basis. The testing includes (1) development of testing scenarios based on threat likelihood and magnitude; (2) consideration of relevant system components from across the entity that can impair availability; (3) scenarios that consider the potential for the lack of availability of key personnel; and (4) revision of resilience posture and continuity plans based on test results.
', NULL),
('CC8.1', 'Common', '8.0 – Common Criteria Related to Change Management', 'The entity authorizes, designs, develops or acquires, configures, documents, tests, approves, and implements changes to infrastructure, data, software, and procedures to meet its objectives.', '• Manages Changes Throughout the System Life Cycle — A process for managing system changes throughout the life cycle of the system and its components (infrastructure, data, software, and manual and automated procedures) is used to support the achievement of entity objectives. • Authorizes Changes — A process is in place to authorize system and architecture changes prior to design, development, or acquisition and configuration. • Designs and Develops Changes — A process is in place to design and develop system changes in a secure manner to support the achievement of entity objectives. • Documents Changes — A process is in place to document system changes to support ongoing maintenance of the system and to support internal and external users in performing their responsibilities. • Tracks System Changes — A process is in place to track system changes prior to implementation. • Configures Software — A process is in place to select, implement, maintain, and monitor configuration parameters used to control the functionality of developed and acquired software. • Tests System Changes — A process is in place to test internally developed and acquired system changes prior to implementation into the production environment. Examples of testing may include unit, integration, regression, static and dynamic application source code, quality assurance, or automated testing (whether point in time or continuous). 
• Approves System Changes — A process is in place to approve system changes prior to implementation. • Deploys System Changes — A process is in place to implement system changes with consideration of segregation of responsibilities (for example, restricting unilateral code development or testing and implementation by a single user) to prevent or detect unauthorized changes. • Identifies and Evaluates System Changes — Objectives affected by system changes are identified, and the ability of the modified system to support the achievement of the objectives is evaluated throughout the system development life cycle. • Identifies Changes in Infrastructure, Data, Software, and Procedures Required to Remediate Incidents — Changes in infrastructure, data, software, and procedures required to remediate incidents are identified and the change process is initiated upon identification. • Creates Baseline Configuration of IT Technology — A baseline configuration of IT and control systems is created and maintained. • Provides for Changes Necessary in Emergency Situations — A process is in place for authorizing, designing, testing, approving, and implementing changes necessary in emergency situations (that is, changes that need to be implemented in an urgent time frame). • Manages Patch Changes — A process is in place to identify, evaluate, test, approve, and implement patches in a timely manner on infrastructure and software. 	
', '• Considers System Resilience — The entity considers system resilience when designing its systems and tests resilience during development to help ensure the entity’s ability to respond to, recover from, and resume operations through significant disruptions. 
• Protects Confidential Information — The entity protects confidential information during system design, development, testing, implementation, and change processes to support the achievement of the entity’s objectives related to confidentiality. 
• Protects Personal Information — The entity protects personal information during system design, development, testing, implementation, and change processes to support the achievement of the entity’s objectives related to privacy. • Privacy by Design — The entity considers privacy requirements in the design of its systems and processes and limits the collection and processing of personal information to what is necessary for the identified purpose. 
'),
('CC9.1', 'Common', '9.0 – Common Criteria Related to Risk Mitigation', 'The entity identifies, selects, and develops risk mitigation activities for risks arising from potential business disruptions.', '• Establishes Requirements for Vendor and Business Partner Engagements — The entity establishes specific requirements for vendor and business partner engagements that include (1) scope of services and product specifications, (2) roles and responsibilities, (3) compliance requirements, and (4) service levels. • Identifies Vulnerabilities — The entity evaluates vulnerabilities arising from vendor and business partner relationships, including third-party access to the entity’s IT systems and connections with third-party networks. • Assesses Vendor and Business Partner Risks — The entity inventories, tiers, and assesses, on a periodic basis, threats arising from relationships with vendors and business partners (and those entities’ vendors and business partners) and the vulnerability of the entity''s objectives to those threats. Examples of threats arising from relationships with vendors and business partners include those arising from their (1) financial failure, (2) security vulnerabilities, (3) operational disruption, and (4) failure to meet business or regulatory requirements. • Assigns Responsibility and Accountability for Managing Vendors and Business Partners — The entity assigns responsibility and accountability for the management of risks and changes to services associated with vendors and business partners. • Establishes Communication Protocols for Vendors and Business Partners — The entity establishes communication and resolution protocols for service or product issues related to vendors and business partners. • Establishes Exception Handling Procedures From Vendors and Business Partners — The entity establishes exception handling procedures for service or product issues related to vendors and business partners. • Assesses Vendor and Business Partner Performance — The entity assesses the performance of vendors and business partners, as frequently as warranted, based on the risk associated with the vendor or business partner. 
• Implements Procedures for Addressing Issues Identified During Vendor and Business Partner Assessments — The entity implements procedures for addressing issues identified with vendor and business partner relationships. • Implements Procedures for Terminating Vendor and Business Partner Relationships — The entity implements procedures for terminating vendor and business partner relationships based on predefined considerations. Those procedures may include safe return of data and its removal from the vendor or business partner system. 
', '• Obtains Confidentiality Commitments From Vendors and Business Partners — The entity obtains confidentiality commitments that are consistent with the entity’s confidentiality commitments and requirements from vendors and business partners who have access to confidential information. • Assesses Compliance With Confidentiality Commitments of Vendors and Business Partners — On a periodic and as-needed basis, the entity assesses compliance by vendors and business partners with the entity’s confidentiality commitments and requirements. 
• Obtains Privacy Commitments From Vendors and Business Partners — The entity obtains privacy commitments, consistent with the entity’s privacy commitments and requirements, from vendors and business partners who have access to personal information. • Assesses Compliance With Privacy Commitments of Vendors and Business Partners — On a periodic and as-needed basis, the entity assesses compliance by vendors and business partners with the entity’s privacy commitments and requirements and takes corrective action as necessary. 
'),
('CC9.2', 'Common', '9.0 – Common Criteria Related to Risk Mitigation', 'The entity assesses and manages risks associated with vendors and business partners.', '• Establishes Requirements for Vendor and Business Partner Engagements — The entity establishes specific requirements for vendor and business partner engagements that include (1) scope of services and product specifications, (2) roles and responsibilities, (3) compliance requirements, and (4) service levels. • Identifies Vulnerabilities — The entity evaluates vulnerabilities arising from vendor and business partner relationships, including third-party access to the entity’s IT systems and connections with third-party networks. • Assesses Vendor and Business Partner Risks — The entity inventories, tiers, and assesses, on a periodic basis, threats arising from relationships with vendors and business partners (and those entities’ vendors and business partners) and the vulnerability of the entity''s objectives to those threats. Examples of threats arising from relationships with vendors and business partners include those arising from their (1) financial failure, (2) security vulnerabilities, (3) operational disruption, and (4) failure to meet business or regulatory requirements. • Assigns Responsibility and Accountability for Managing Vendors and Business Partners — The entity assigns responsibility and accountability for the management of risks and changes to services associated with vendors and business partners. • Establishes Communication Protocols for Vendors and Business Partners — The entity establishes communication and resolution protocols for service or product issues related to vendors and business partners. • Establishes Exception Handling Procedures From Vendors and Business Partners — The entity establishes exception handling procedures for service or product issues related to vendors and business partners. • Assesses Vendor and Business Partner Performance — The entity assesses the performance of vendors and business partners, as frequently as warranted, based on the risk associated with the vendor or business partner. 
• Implements Procedures for Addressing Issues Identified During Vendor and Business Partner Assessments — The entity implements procedures for addressing issues identified with vendor and business partner relationships. • Implements Procedures for Terminating Vendor and Business Partner Relationships — The entity implements procedures for terminating vendor and business partner relationships based on predefined considerations. Those procedures may include safe return of data and its removal from the vendor or business partner system. 
', '• Obtains Confidentiality Commitments From Vendors and Business Partners — The entity obtains confidentiality commitments that are consistent with the entity’s confidentiality commitments and requirements from vendors and business partners who have access to confidential information. • Assesses Compliance With Confidentiality Commitments of Vendors and Business Partners — On a periodic and as-needed basis, the entity assesses compliance by vendors and business partners with the entity’s confidentiality commitments and requirements. 
• Obtains Privacy Commitments From Vendors and Business Partners — The entity obtains privacy commitments, consistent with the entity’s privacy commitments and requirements, from vendors and business partners who have access to personal information. • Assesses Compliance With Privacy Commitments of Vendors and Business Partners — On a periodic and as-needed basis, the entity assesses compliance by vendors and business partners with the entity’s privacy commitments and requirements and takes corrective action as necessary. 
'),
('PI1.1', 'Processing Integrity', NULL, 'The entity implements policies and procedures over system processing to result in products, ser- vices, and reporting to meet the entity’s objectives.
', '        • _Defines Processing Specifications — The processing specifications that are neces- sary to meet product or service requirements are defined. _
     • _Defines Processing Activities — Processing activities are defined to result in prod- ucts or services that meet specifications. _
      _Detects and Corrects Processing or Production Activity Errors — Errors encoun- tered in processing or production activities are detected and corrected in a timely manner. _
     • _Records System Processing Activities — System processing activities are recorded completely and accurately in a timely manner. _
     • _Processes Inputs — Inputs are processed completely, accurately, and timely as au- thorized in accordance with defined processing activities. _
  
', NULL),
('PI1.2', 'Processing Integrity', NULL, 'The entity implements policies and procedures over system inputs, including controls over com- pleteness and accuracy, to result in products, services, and reporting to meet the entity’s objectives.', '**The following points of focus, which apply only to an engagement using the trust services crite- ria for processing integrity, highlight important characteristics relating to this criterion: **
    • _Defines Characteristics of Processing Inputs — The characteristics of processing inputs that are necessary to meet requirements are defined. _
     • _Evaluates Processing Inputs — Processing inputs are evaluated for compliance with defined input requirements. _
     • _Creates and Maintains Records of System Inputs — Records of system input activi- ties are created and maintained completely and accurately in a timely manner. _
  
', NULL),
('PI1.3', 'Processing Integrity', NULL, 'The entity implements policies and procedures over system processing to result in products, ser- vices, and reporting to meet the entity’s objectives.', ' _Protects Output — Output is protected when stored or delivered, or both, to prevent theft, destruction, corruption, or deterioration that would prevent output from meet- ing specifications. _
     • _Distributes Output Only to Intended Parties — Output is distributed or made avail- able only to intended parties. _
     • _Distributes Output Completely and Accurately — Procedures are in place to pro- vide for the completeness, accuracy, and timeliness of distributed output. _
     • _Creates and Maintains Records of System Output Activities — Records of system output activities are created and maintained completely and accurately in a timely manner. _


', NULL),
('PI1.4', 'Processing Integrity', NULL, 'The entity implements policies and procedures to make available or deliver output completely, accu- rately, and timely in accordance with specifications to meet the entity’s objectives.
', '    _Protects Output — Output is protected when stored or delivered, or both, to prevent theft, destruction, corruption, or deterioration that would prevent output from meet- ing specifications. _
     • _Distributes Output Only to Intended Parties — Output is distributed or made avail- able only to intended parties. _
     • _Distributes Output Completely and Accurately — Procedures are in place to pro- vide for the completeness, accuracy, and timeliness of distributed output. _
     • _Creates and Maintains Records of System Output Activities — Records of system output activities are created and maintained completely and accurately in a timely manner. _
    
', NULL),
('PI1.5', 'Processing Integrity', NULL, 'The entity implements policies and procedures to store inputs, items in processing, and outputs completely, accurately, and timely in accordance with system specifications to meet the entity’s ob- jectives.
', '**The following points of focus, which apply only to an engagement using the trust services crite- ria for processing integrity, highlight important characteristics relating to this criterion: **
    _Protects Stored Items — Stored items are protected to prevent theft, corruption, de- struction, or deterioration that would prevent output from meeting specifications. _
     • _Archives and Protects System Records — System records are archived, and archives are protected against theft, corruption, destruction, or deterioration that would pre- vent them from being used. _
     • _Stores Data Completely and Accurately — Procedures are in place to provide for the complete, accurate, and timely storage of data. _
     • _Creates and Maintains Records of System Storage Activities — Records of system storage activities are created and maintained completely and accurately in a timely manner. _
  
', NULL)

on conflict (tsc_code) do update set
  trust_principle            = excluded.trust_principle,
  common_criteria_category   = excluded.common_criteria_category,
  description                = excluded.description,
  points_of_focus            = excluded.points_of_focus,
  additional_points_of_focus = excluded.additional_points_of_focus;
